# Generated by Django 5.1.9 on 2025-05-08 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=1)),
                ('explanation', models.TextField()),
                ('difficulty', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science'), ('English', 'English'), ('History', 'History'), ('Algorithms', 'Algorithms'), ('Computer Science', 'Computer Science'), ('Web Development', 'Web Development'), ('Other', 'Other')], max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
