# Generated by Django 5.1.4 on 2025-02-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempt_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
