# Generated by Django 5.1.4 on 2025-02-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmcq',
            name='order',
            field=models.IntegerField(),
        ),
    ]
