# Generated by Django 5.1.4 on 2025-02-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_test', '0002_alter_testmcq_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmcq',
            name='order',
            field=models.PositiveBigIntegerField(),
        ),
    ]
